
title: "Siri Lahari"
description: "Notes on Data Science, AI, and projects — by Siri Lahari"
url: "https://sirilahari.com"
baseurl: ""

# Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes"

# Author profile (shows on home/about)
author:
  name: "Siri Lahari"
  avatar: "/assets/images/avatar.jpg"  # replace with your image
  bio: "Data Science + AI — building, learning, sharing."
  location: "USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your-email@example.com"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation
# Uses _data/navigation.yml
# Collections (optional) can be added later for projects/portfolio.
paginate: 5

# Google Analytics (optional)
# google_analytics: ""

# Social sharing (optional thumbnail)
# og_image: /assets/images/og.jpg
